name: Creates Drupal Core artifact
runs:
  using: 'composite'
  steps:
    - name: "Install PHP"
      uses: "shivammathur/setup-php@v2"
      with:
        coverage: "none"
        php-version: "8.3"
    - name: composer create-project
      shell: bash
      run: |
        composer create-project drupal/recommended-project:^10 drupal-core --no-install
    - name: process build
      shell: bash
      run: |
        cd drupal-core
        composer config --merge --json 'extra.drupal-scaffold.file-mapping' '{"[project-root]/.gitattributes": {"append": "../patches/.gitattributes"}}'
        composer config --merge --json 'extra.drupal-scaffold.file-mapping' '{"[web-root]/sites/default/default.settings.php": {"append": "../patches/default.settings.php"}}'
        composer config --merge --json 'extra.patches.drupal/core' '{"Remove Fibers from Renderer": "../patches/renderer-remove-fibers.patch"}'
        composer config --merge --json 'extra.patches.drupal/core' '{"Remove file_system service usage from SQLite installer": "../patches/sqlite-file_system-service.patch"}'
        composer config --merge --json 'extra.patches.drupal/core' '{"Use base_path global in unrouted url assembled": "../patches/unrouted-url-base_path.patch"}'
        composer config --merge --json 'extra.patches.drupal/core' '{"Reqs to OK": "../patches/system-reqs-wasm.patch"}'
        composer config --merge --json 'extra.patches.drupal/core' '{"Install to batch base: fix": "../patches/install-core-base-path-url-batch.patch"}'
        
        composer require cweagans/composer-patches --no-install
        composer config --no-plugins allow-plugins.cweagans/composer-patches true
        
        composer install --no-dev
    - name: composer archive
      shell: bash
      run: cd drupal-core && composer archive --format=zip --file=drupal-core
