name: "Deploy"
on:
  push:
    branches:
      - main
concurrency: deploy
jobs:
  build:
    name: "Build & deploy"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.3"
      - name: "build"
        run: make build
      - name: "configure AWS"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy
        working-directory: ./playground
        run: aws s3 sync ./public s3://wasm-drupal
      - name: Invalidate CloudFront
        working-directory: ./playground
        run: aws cloudfront create-invalidation --distribution-id ENEVO72R9T6H5 --paths "/*"
