name: Drupal build
on:
  workflow_call:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/drupal_build.yml'
      - 'drupal-src/**'
jobs:
  drupal_build:
    name: "Build artifact"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.3"
      - name: "build"
        run: make drupal-archive
      - name: Upload artifact archive
        uses: actions/upload-artifact@v4
        with:
          name: drupal-artifact
          path: drupal-wasm-1.0.zip
