name: "Deploy Drupal artifact"
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/drupal_build.yml'
      - '.github/workflows/drupal_deploy.yml'
      - 'drupal-src/**'
concurrency: drupal_deploy
jobs:
  build:
    uses: ./.github/workflows/drupal_build.yml
  deploy:
    name: "Build & deploy"
    runs-on: "ubuntu-latest"
    needs: [build]
    steps:
      - name: Download Drupal artifact
        uses: actions/download-artifact@v4
        with:
          name: drupal-artifact
      - name: "configure AWS"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy
        run: aws s3 cp drupal.zip s3://wasm-drupal/assets/drupal.zip
      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ENEVO72R9T6H5 --paths "/assets/drupal.zip"
