name: "Drupal Core Artifact"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
concurrency: starshot
jobs:
  build:
    name: "Build drupal-core"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.3"
      - run: |
          composer create-project drupal/recommended-project:^10 drupal-core --no-install
      - run: |
          cd drupal-core
          composer config --merge --json 'extra.drupal-scaffold.file-mapping' '{"[project-root]/.gitattributes": {"append": "../patches/.gitattributes"}}'
          composer config --merge --json 'extra.patches.drupal/core' '{"Remove Fibers from Renderer": "../patches/renderer-remove-fibers.patch"}'
          composer config --merge --json 'extra.patches.drupal/core' '{"Remove file_system service usage from SQLite installer": "../patches/sqlite-file_system-service.patch"}'

          composer install --no-dev

          cp web/sites/example.settings.local.php web/sites/default/settings.local.php
          cp web/sites/default/default.settings.php web/sites/default/settings.php
          echo "include \$app_root . '/' . \$site_path . '/settings.local.php';" >> web/sites/default/settings.php

      - run: cd drupal-core && composer archive --format=zip --file=drupal-core
      - name: Upload prototype archive
        uses: actions/upload-artifact@v4
        with:
          name: drupal-core
          path: |
            drupal-core/drupal-core.zip
      - name: "configure AWS"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload artifact
        run: aws s3 cp drupal-core/drupal-core.zip s3://wasm-drupal/assets/drupal-core.zip
      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ENEVO72R9T6H5 --paths "/assets/drupal-core.zip"
