name: "Starshot"
on: workflow_dispatch
concurrency: starshot
jobs:
  build:
    name: "Build starshot"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout prototype"
        uses: actions/checkout@v4
        with:
          repository: phenaproxima/starshot-prototype
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.3"
      - run: composer install
      - run: composer drupal:install
      - run: php vendor/bin/drush pm-uninstall big_pipe --yes
      - run: composer archive --format=zip
      - name: Upload prototype archive
        uses: actions/upload-artifact@v4
        with:
          name: starshot
          path: |
            drupal-starshot-project*.zip
      - name: "configure AWS"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload artifact
        run: aws s3 sync ./drupal-starshot-project*.zip s3://wasm-drupal
