name: "Starshot"
on: workflow_dispatch
concurrency: starshot
jobs:
  build:
    name: "Build starshot"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout prototype"
        uses: actions/checkout@v4
        with:
          repository: phenaproxima/starshot-prototype
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.3"
      - run: |
          curl https://raw.githubusercontent.com/mglaman/wasm-drupal/main/drupal-src/patches/.gitattributes -o gitattributes-append
          composer config --merge --json 'extra.drupal-scaffold.file-mapping' '{"[project-root]/.gitattributes": {"append": "gitattributes-append"}}'
      - run: composer install
      - run: composer drupal:install
      - run: php vendor/bin/drush pm-uninstall big_pipe --yes
      - run: composer archive --format=zip --file=drupal-starshot --dir=/tmp
      - name: Upload prototype archive
        uses: actions/upload-artifact@v4
        with:
          name: starshot
          path: |
            /tmp/drupal-starshot.zip
      - name: "configure AWS"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload artifact
        run: aws s3 sync /tmp/drupal-starshot.zip s3://wasm-drupal
