name: "Starshot"
on: workflow_dispatch
concurrency: starshot
jobs:
  build:
    name: "Build starshot"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout prototype"
        uses: actions/checkout@v4
        with:
          repository: phenaproxima/starshot-prototype
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.3"
      - run: |
          curl https://raw.githubusercontent.com/mglaman/wasm-drupal/main/drupal-src/patches/.gitattributes -o gitattributes-append
          composer config --merge --json 'extra.drupal-scaffold.file-mapping' '{"[project-root]/.gitattributes": {"append": "gitattributes-append"}}'
      - run: |
          curl -O https://raw.githubusercontent.com/mglaman/wasm-drupal/main/drupal-src/patches/drupal-kernel-remove-ini_set.patch
          composer config --merge --json 'extra.patches.drupal/core' '{"Remove ini_set calls": "./drupal-kernel-remove-ini_set.patch"}'
      - run: |
          curl -O https://raw.githubusercontent.com/mglaman/wasm-drupal/main/drupal-src/patches/renderer-remove-fibers.patch
          composer config --merge --json 'extra.patches.drupal/core' '{"Remove Fibers from Renderer": "./renderer-remove-fibers.patch"}'
      - run: composer install --no-dev
      - run: |
          curl -O https://raw.githubusercontent.com/mglaman/wasm-drupal/main/drupal-src/web/sites/default/settings.local.php
          mv settings.local.php web/sites/default

          cp web/sites/default/default.settings.php web/sites/default/settings.php
          echo "include \$app_root . '/' . \$site_path . '/settings.local.php';" >> web/sites/default/settings.php
      - run: composer drupal:install
      - run: php vendor/bin/drush pm-uninstall big_pipe --yes
      - run: |
          rm gitattributes-append *.patch
      - run: composer archive --format=zip --file=drupal-starshot
      - name: Upload prototype archive
        uses: actions/upload-artifact@v4
        with:
          name: starshot
          path: |
            drupal-starshot.zip
      - name: "configure AWS"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload artifact
        run: aws s3 cp drupal-starshot.zip s3://wasm-drupal/assets/drupal-starshot.zip
