name: Web build
on:
  workflow_call:
  pull_request:
    branches:
      - main
jobs:
  web_build:
    name: "Build artifact"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: "build"
        run: make demo-build
      - name: Download Drupal Core artifact
        uses: actions/download-artifact@v4
        with:
          name: drupal-core
          path: tests/fixtures/persist
      - name: "test"
        run: make demo-test
      - name: Upload demo archive
        uses: actions/upload-artifact@v4
        with:
          name: demo
          path: public
