name: "Deploy"
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/web_build.yml'
      - '.github/workflows/web_deploy.yml'
      - 'playground/**'
concurrency: web_deploy
jobs:
  build:
    uses: ./.github/workflows/web_build.yml
  deploy:
    name: "Build & deploy"
    runs-on: "ubuntu-latest"
    needs: [build]
    steps:
      - name: Download Drupal artifact
        uses: actions/download-artifact@v4
        with:
          name: playground
      - name: "configure AWS"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy
        working-directory: ./playground
        run: aws s3 sync ./public s3://wasm-drupal
      - name: Invalidate CloudFront
        working-directory: ./playground
        run: aws cloudfront create-invalidation --distribution-id ENEVO72R9T6H5 --paths "/*"
